### ISSUE TITLE
Advantages over dict.parse_json()?

### ISSUE THREAD

**Issue by Sandvich** [DeadlyLampshade/godot-db#1]
Hi!
I'm just wondering, awesome though it is, what advantages this library gives a developer over the built in dict.parse_json()? Am I completely missing the aim of this library?
Thanks!
Sanchit

**Comment by DeadlyLampshade** [comment]
`dict.parse_json()` is not available in Godot 3.0, which this plugin is made for.

**Comment by DeadlyLampshade** [comment]
Okay I understand your question a bit better.

The question is that this is an easy, visual means of writing a JSON files. If you're happy with writing JSON files yourself, by all means, keep doing it.

**Comment by Sandvich** [comment]
Nope, your first answer is what I wanted - I didn't realise dict.parse_json() was removed in 3.0!
I'm still on 2.x right now...

Thanks!
